zfrom pathlib import Path
p = Path(r'c:/Users/Agyemang Rendolf/Desktop/Shipping Company/Templates/index.html')
text = p.read_text(encoding='utf-8')
needle = "                {\n                    tracking_number: 'RBH-0002',\n                    asset_description: 'Diamond Shipment - Box A',\n                    shipment_status: 'Delivered',\n                    customs_status: 'Cleared',\n                    duties_taxes: '$0',\n                    insurance_status: 'Claimed',\n                    security_level: 'Top',\n                    receiver_status: 'Signed',\n                    last_location: 'Zurich Vault',\n                    customs_agent: 'Agent Z',\n                    agent_id: 'AG-202',\n                    notice_text: '',\n                    shipment_date: '2026-05-20',\n                    expected_date: '2026-05-22'\n                }\n            ];\n"
if needle not in text:
    raise ValueError('Needle not found in index.html')
replacement = "                {\n                    tracking_number: 'RBH-0002',\n                    asset_description: 'Diamond Shipment - Box A',\n                    shipment_status: 'Delivered',\n                    customs_status: 'Cleared',\n                    duties_taxes: '$0',\n                    insurance_status: 'Claimed',\n                    security_level: 'Top',\n                    receiver_status: 'Signed',\n                    last_location: 'Zurich Vault',\n                    customs_agent: 'Agent Z',\n                    agent_id: 'AG-202',\n                    notice_text: '',\n                    shipment_date: '2026-05-20',\n                    expected_date: '2026-05-22'\n                },\n                {\n                    tracking_number: 'GBX-2026-458721',\n                    asset_description: 'Secure Vault Transfer - Sovereign Cargo',\n                    shipment_status: 'In Transit',\n                    customs_status: 'Awaiting Clearance',\n                    duties_taxes: '$18,900',\n                    insurance_status: 'Insured',\n                    security_level: 'Critical',\n                    receiver_status: 'Pending',\n                    last_location: 'Dubai Secure Hub',\n                    customs_agent: 'Agent K',\n                    agent_id: 'AG-421',\n                    notice_text: 'Priority cargo under enhanced customs watch.',\n                    shipment_date: '2026-06-02',\n                    expected_date: '2026-06-12'\n                }\n            ];\n"
text = text.replace(needle, replacement)
text = text.replace("alert('Sample shipments added to localStorage. Use RBH-0001 or RBH-0002 to test.')", "alert('Sample shipments added to localStorage. Use RBH-0001, RBH-0002 or GBX-2026-458721 to test.')")
p.write_text(text, encoding='utf-8')
print('patched')
