services:
  - type: web
    name: speed-shipping-security
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: RBH_SECRET_KEY
        generateValue: true
      - key: RBH_ADMIN_USER
        value: Rendolf_001
      - key: RBH_ADMIN_PASS
        value: iwasmadeforthisshid$$
